[versions]
agp = "8.3.0"
kotlin = "1.9.22"
firebaseInappmessaging = "22.0.2"
[libraries]
firebase-inappmessaging = { group = "com.google.firebase", name = "firebase-inappmessaging", version.ref = "firebaseInappmessaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }